### ISSUE TITLE
crash on server 

### ISSUE THREAD

**Issue by MehanikTMYT** [alec016/Applied-Experienced#1]
-- Mod loading issue for: appex --
Details:
	Mod file: /content/gdrive/MyDrive/server/mods/applied-experienced-1.21.1-1.0.1.jar
	Failure message: Applied Experienced (appex) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
		java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:item / appex:experience_acceptor]
	Mod version: 1.0.1
	Mod issues URL: <No issues URL found>
	Exception message: java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:item / appex:experience_acceptor]
Stacktrace:
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredHolder.value(DeferredHolder.java:103) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredHolder.get(DeferredHolder.java:117) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/ae2@19.1.1-beta/appeng.core.definitions.ItemDefinition.asItem(ItemDefinition.java:114) ~[appliedenergistics2-19.1.1-beta.jar%23308!/:?] {re:classloading}
	at TRANSFORMER/ae2@19.1.1-beta/appeng.core.definitions.BlockDefinition.asItem(BlockDefinition.java:83) ~[appliedenergistics2-19.1.1-beta.jar%23308!/:?] {re:classloading}
	at TRANSFORMER/appex@1.0.1/es.degrassi.appexp.definition.AExpBlockEntities.lambda$create$3(AExpBlockEntities.java:63) ~[applied-experienced-1.21.1-1.0.1.jar%23306!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:215) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$1(DeferredRegister.java:234) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$addEntries$2(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.RegisterEvent.register(RegisterEvent.java:48) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.addEntries(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:92) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}

**Comment by alec016** [comment]
can you try with this version and see if it persists? https://we.tl/t-KWxg2pr9yW
